// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UczelniaAPI.Models;

#nullable disable

namespace UczelniaAPI.Migrations
{
    [DbContext(typeof(UczelniaContext))]
    [Migration("20230116221710_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UczelniaAPI.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<int>("IdStudia")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NrIndeksu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("int");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdStudia");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            IdStudent = 1,
                            IdStudia = 1,
                            Imie = "Anna",
                            Nazwisko = "Kowalska",
                            NrIndeksu = "A001",
                            RokStudiow = 3
                        },
                        new
                        {
                            IdStudent = 2,
                            IdStudia = 1,
                            Imie = "Jan",
                            Nazwisko = "Nowak",
                            NrIndeksu = "A002",
                            RokStudiow = 2
                        },
                        new
                        {
                            IdStudent = 3,
                            IdStudia = 2,
                            Imie = "Katarzyna",
                            Nazwisko = "Wiśniewska",
                            NrIndeksu = "A003",
                            RokStudiow = 4
                        },
                        new
                        {
                            IdStudent = 4,
                            IdStudia = 2,
                            Imie = "Piotr",
                            Nazwisko = "Wojtyła",
                            NrIndeksu = "A004",
                            RokStudiow = 1
                        },
                        new
                        {
                            IdStudent = 5,
                            IdStudia = 3,
                            Imie = "Agnieszka",
                            Nazwisko = "Kowalczyk",
                            NrIndeksu = "A005",
                            RokStudiow = 3
                        },
                        new
                        {
                            IdStudent = 6,
                            IdStudia = 3,
                            Imie = "Adam",
                            Nazwisko = "Majewski",
                            NrIndeksu = "A006",
                            RokStudiow = 2
                        },
                        new
                        {
                            IdStudent = 7,
                            IdStudia = 4,
                            Imie = "Ewa",
                            Nazwisko = "Kozłowska",
                            NrIndeksu = "A007",
                            RokStudiow = 4
                        },
                        new
                        {
                            IdStudent = 8,
                            IdStudia = 4,
                            Imie = "Tomasz",
                            Nazwisko = "Jabłoński",
                            NrIndeksu = "A008",
                            RokStudiow = 1
                        },
                        new
                        {
                            IdStudent = 9,
                            IdStudia = 5,
                            Imie = "Magdalena",
                            Nazwisko = "Wróbel",
                            NrIndeksu = "A009",
                            RokStudiow = 3
                        },
                        new
                        {
                            IdStudent = 10,
                            IdStudia = 5,
                            Imie = "Dariusz",
                            Nazwisko = "Kaczmarek",
                            NrIndeksu = "A010",
                            RokStudiow = 2
                        },
                        new
                        {
                            IdStudent = 11,
                            IdStudia = 5,
                            Imie = "Adam",
                            Nazwisko = "Szczepanowski",
                            NrIndeksu = "A011",
                            RokStudiow = 1
                        },
                        new
                        {
                            IdStudent = 12,
                            IdStudia = 7,
                            Imie = "Ewa",
                            Nazwisko = "Kowalska",
                            NrIndeksu = "A012",
                            RokStudiow = 2
                        },
                        new
                        {
                            IdStudent = 13,
                            IdStudia = 7,
                            Imie = "Jan",
                            Nazwisko = "Nowak",
                            NrIndeksu = "A013",
                            RokStudiow = 3
                        },
                        new
                        {
                            IdStudent = 14,
                            IdStudia = 7,
                            Imie = "Anna",
                            Nazwisko = "Kowalska",
                            NrIndeksu = "A014",
                            RokStudiow = 4
                        },
                        new
                        {
                            IdStudent = 15,
                            IdStudia = 8,
                            Imie = "Katarzyna",
                            Nazwisko = "Wiśniewska",
                            NrIndeksu = "A015",
                            RokStudiow = 5
                        },
                        new
                        {
                            IdStudent = 16,
                            IdStudia = 9,
                            Imie = "Piotr",
                            Nazwisko = "Wojtyła",
                            NrIndeksu = "A016",
                            RokStudiow = 1
                        },
                        new
                        {
                            IdStudent = 17,
                            IdStudia = 9,
                            Imie = "Agnieszka",
                            Nazwisko = "Kowalczyk",
                            NrIndeksu = "A017",
                            RokStudiow = 2
                        },
                        new
                        {
                            IdStudent = 18,
                            IdStudia = 9,
                            Imie = "Adam",
                            Nazwisko = "Majewski",
                            NrIndeksu = "A018",
                            RokStudiow = 3
                        },
                        new
                        {
                            IdStudent = 19,
                            IdStudia = 10,
                            Imie = "Ewa",
                            Nazwisko = "Kozłowska",
                            NrIndeksu = "A019",
                            RokStudiow = 4
                        },
                        new
                        {
                            IdStudent = 20,
                            IdStudia = 10,
                            Imie = "Tomasz",
                            Nazwisko = "Jabłoński",
                            NrIndeksu = "A020",
                            RokStudiow = 5
                        });
                });

            modelBuilder.Entity("UczelniaAPI.Models.Studia", b =>
                {
                    b.Property<int>("IdStudia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudia"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tryb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdStudia");

                    b.ToTable("Studies");

                    b.HasData(
                        new
                        {
                            IdStudia = 1,
                            Nazwa = "Informatyka",
                            Tryb = "Stacjonarny"
                        },
                        new
                        {
                            IdStudia = 2,
                            Nazwa = "Ekonomia",
                            Tryb = "Niestacjonarny"
                        },
                        new
                        {
                            IdStudia = 3,
                            Nazwa = "Zarządzanie",
                            Tryb = "Stacjonarny"
                        },
                        new
                        {
                            IdStudia = 4,
                            Nazwa = "Prawo",
                            Tryb = "Niestacjonarny"
                        },
                        new
                        {
                            IdStudia = 5,
                            Nazwa = "Architektura",
                            Tryb = "Stacjonarny"
                        },
                        new
                        {
                            IdStudia = 6,
                            Nazwa = "Mechanika",
                            Tryb = "Niestacjonarny"
                        },
                        new
                        {
                            IdStudia = 7,
                            Nazwa = "Fizyka",
                            Tryb = "Stacjonarny"
                        },
                        new
                        {
                            IdStudia = 8,
                            Nazwa = "Matematyka",
                            Tryb = "Niestacjonarny"
                        },
                        new
                        {
                            IdStudia = 9,
                            Nazwa = "Chemia",
                            Tryb = "Stacjonarny"
                        },
                        new
                        {
                            IdStudia = 10,
                            Nazwa = "Biologia",
                            Tryb = "Niestacjonarny"
                        });
                });

            modelBuilder.Entity("UczelniaAPI.Models.Student", b =>
                {
                    b.HasOne("UczelniaAPI.Models.Studia", "Studia")
                        .WithMany("Studenci")
                        .HasForeignKey("IdStudia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studia");
                });

            modelBuilder.Entity("UczelniaAPI.Models.Studia", b =>
                {
                    b.Navigation("Studenci");
                });
#pragma warning restore 612, 618
        }
    }
}
